
services:
  # Nginx Proxy Manager - Web UI for proxy and SSL management
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'      # HTTP
      - '443:443'    # HTTPS
      - '81:81'      # Admin Web Port
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    environment:
      DISABLE_IPV6: 'true'
    networks:
      - proxy-network

  # Baseball Scouting Application
  app:
    build: .
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=baseball_scouting
      - DB_USER=scout_user
      - DB_PASSWORD=${DB_PASSWORD:-scout_pass}
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET:-change-this-in-production}
      - DOMAIN=${DOMAIN:-baseballscoutingreports.com}
    volumes:
      - app_uploads:/app/uploads
    depends_on:
      - db
    networks:
      - proxy-network
      - app-network
    # Note: No ports exposed - accessed through nginx-proxy-manager

  # MongoDB Database
  db:
    image: mongo:7-jammy
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=scout_user
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-scout_pass}
      - MONGO_INITDB_DATABASE=baseball_scouting
    volumes:
      - mongo_data:/data/db
      - ./backups:/backups
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network
    # Database not exposed to internet

volumes:
  mongo_data:
  npm_data:
  npm_letsencrypt:
  app_uploads:

networks:
  proxy-network:
    driver: bridge
  app-network:
    driver: bridge
    internal: true  # Database network isolated from internet